{"timestamp":"2025-08-25T12:37:42.107647","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-25T12:37:42.121023","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/ELT.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-25T12:37:50.113126","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"AirflowRuntimeError","exc_value":"API_SERVER_ERROR: {'status_code': 409, 'message': 'Server returned error', 'detail': {'detail': {'reason': 'Unique constraint violation', 'statement': 'INSERT INTO rendered_task_instance_fields (dag_id, task_id, run_id, map_index, rendered_fields, k8s_pod_yaml) VALUES (%(dag_id)s, %(task_id)s, %(run_id)s, %(map_index)s, %(rendered_fields)s, %(k8s_pod_yaml)s)', 'orig_error': 'duplicate key value violates unique constraint \"rendered_task_instance_fields_pkey\"\\nDETAIL:  Key (dag_id, task_id, run_id, map_index)=(ELT_pipeline_com_dbt8, extraction_task, scheduled__2025-08-25T00:00:00+00:00, 1) already exists.\\n', 'message': 'Serious error when handling your request. Check logs for more details - you will find it in api server when you look for ID DZMXePoY'}}}","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":884,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":778,"name":"_prepare"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/comms.py","lineno":203,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/comms.py","lineno":263,"name":"_get_response"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/comms.py","lineno":250,"name":"_from_frame"}],"is_group":false,"exceptions":[]}]}
